version: '3'

services:
  # Node Container
  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server/src:/srv/app/ebay-server/src
    command: yarn dev
  
  # Client Container
  client: 
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose: 
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/srv/app/ebay-client/src
      - ./client/public:/srv/app/ebay-client/public
    links:
      - server
    command: yarn start